import { PackItem, Tip } from './types';

export const DEFAULT_ITEMS: PackItem[] = [
  // Kleding
  { id: 'c1', name: 'Wandelschoenen', category: 'Kleding', tripTypes: ['weekend', 'week', 'wandeldag', 'wandeltrip'], mountains: false, kids: false },
  { id: 'c2', name: 'Regenjas', category: 'Kleding', tripTypes: ['weekend', 'week', 'wandeldag', 'wandeltrip'], mountains: false, kids: false },
  { id: 'c3', name: 'Thermokleding (ondershirts)', category: 'Kleding', tripTypes: ['weekend', 'week', 'wandeldag', 'wandeltrip'], mountains: true, kids: false },
  { id: 'c4', name: 'Fleece vest', category: 'Kleding', tripTypes: ['weekend', 'week', 'wandeldag', 'wandeltrip'], mountains: true, kids: false },
  { id: 'c5', name: 'Zonnebril', category: 'Kleding', tripTypes: ['weekend', 'week', 'wandeldag', 'wandeltrip'], mountains: false, kids: false },
  { id: 'c6', name: 'Wandelsokken (extra)', category: 'Kleding', tripTypes: ['weekend', 'week', 'wandeldag', 'wandeltrip'], mountains: false, kids: false },
  { id: 'c7', name: 'Zwemkleding', category: 'Kleding', tripTypes: ['weekend', 'week'], mountains: false, kids: false },
  { id: 'c8', name: 'Pet / zonnehoed', category: 'Kleding', tripTypes: ['weekend', 'week', 'wandeldag', 'wandeltrip'], mountains: false, kids: false },
  { id: 'c9', name: 'Handschoenen', category: 'Kleding', tripTypes: ['weekend', 'week', 'wandeldag', 'wandeltrip'], mountains: true, kids: false },
  { id: 'c10', name: 'Muts', category: 'Kleding', tripTypes: ['weekend', 'week', 'wandeldag', 'wandeltrip'], mountains: true, kids: false },
  { id: 'c11', name: 'T-shirts / bovenkledij', category: 'Kleding', tripTypes: ['weekend', 'week', 'wandeldag', 'wandeltrip'], mountains: false, kids: false },
  { id: 'c12', name: 'Onderkleding & sokken', category: 'Kleding', tripTypes: ['weekend', 'week', 'wandeltrip'], mountains: false, kids: false },
  { id: 'c13', name: 'Nachtkleding / pyama', category: 'Kleding', tripTypes: ['weekend', 'week', 'wandeltrip'], mountains: false, kids: false },
  { id: 'c14', name: 'Slippers / badslippers', category: 'Kleding', tripTypes: ['weekend', 'week', 'wandeltrip'], mountains: false, kids: false },

  // Slaap
  { id: 's1', name: 'Tent', category: 'Slaap', tripTypes: ['weekend', 'week'], mountains: false, kids: false },
  { id: 's2', name: 'Slaapzak', category: 'Slaap', tripTypes: ['weekend', 'week'], mountains: false, kids: false },
  { id: 's3', name: 'Slaapmat / luchtbed', category: 'Slaap', tripTypes: ['weekend', 'week'], mountains: false, kids: false },
  { id: 's4', name: 'Kussen', category: 'Slaap', tripTypes: ['weekend', 'week'], mountains: false, kids: false },
  { id: 's5', name: 'Oordopjes', category: 'Slaap', tripTypes: ['weekend', 'week', 'wandeltrip'], mountains: false, kids: false },
  { id: 's6', name: 'Slaapzak kinderen', category: 'Slaap', tripTypes: ['weekend', 'week'], mountains: false, kids: true },

  // Keuken & Eten
  { id: 'k1', name: 'Campingkooktoestel', category: 'Keuken & Eten', tripTypes: ['weekend', 'week'], mountains: false, kids: false },
  { id: 'k2', name: 'Gaspatronen (extra)', category: 'Keuken & Eten', tripTypes: ['weekend', 'week'], mountains: false, kids: false },
  { id: 'k3', name: 'Pannen / kookset', category: 'Keuken & Eten', tripTypes: ['weekend', 'week'], mountains: false, kids: false },
  { id: 'k4', name: 'Bestek & borden', category: 'Keuken & Eten', tripTypes: ['weekend', 'week', 'wandeltrip'], mountains: false, kids: false },
  { id: 'k5', name: 'Mok / thermosbeker', category: 'Keuken & Eten', tripTypes: ['weekend', 'week', 'wandeldag', 'wandeltrip'], mountains: false, kids: false },
  { id: 'k6', name: 'Waterfles (per persoon)', category: 'Keuken & Eten', tripTypes: ['weekend', 'week', 'wandeldag', 'wandeltrip'], mountains: false, kids: false },
  { id: 'k7', name: 'Waterfilter / zuiveringstabletten', category: 'Keuken & Eten', tripTypes: ['week', 'wandeltrip'], mountains: true, kids: false },
  { id: 'k8', name: 'Afwasbak & zeep', category: 'Keuken & Eten', tripTypes: ['weekend', 'week'], mountains: false, kids: false },
  { id: 'k9', name: 'Aansteker / lucifers', category: 'Keuken & Eten', tripTypes: ['weekend', 'week', 'wandeltrip'], mountains: false, kids: false },
  { id: 'k10', name: 'Koelbox / koeltas', category: 'Keuken & Eten', tripTypes: ['weekend', 'week'], mountains: false, kids: false },
  { id: 'k11', name: 'Snacks voor onderweg', category: 'Keuken & Eten', tripTypes: ['weekend', 'week', 'wandeldag', 'wandeltrip'], mountains: false, kids: false },
  { id: 'k12', name: 'Kindersnacks extra', category: 'Keuken & Eten', tripTypes: ['weekend', 'week', 'wandeldag', 'wandeltrip'], mountains: false, kids: true },
  { id: 'k13', name: 'Koffie / thee', category: 'Keuken & Eten', tripTypes: ['weekend', 'week', 'wandeltrip'], mountains: false, kids: false },
  { id: 'k14', name: 'Vuilniszakken', category: 'Keuken & Eten', tripTypes: ['weekend', 'week', 'wandeldag', 'wandeltrip'], mountains: false, kids: false },
  { id: 'k15', name: 'Keukenmes', category: 'Keuken & Eten', tripTypes: ['weekend', 'week', 'wandeltrip'], mountains: false, kids: false },
  { id: 'k16', name: 'Snijplank', category: 'Keuken & Eten', tripTypes: ['weekend', 'week'], mountains: false, kids: false },
  { id: 'k17', name: 'Scheplepel / spatel', category: 'Keuken & Eten', tripTypes: ['weekend', 'week'], mountains: false, kids: false },
  { id: 'k18', name: 'Blikopener', category: 'Keuken & Eten', tripTypes: ['weekend', 'week', 'wandeltrip'], mountains: false, kids: false },
  { id: 'k19', name: 'Keukenrol', category: 'Keuken & Eten', tripTypes: ['weekend', 'week'], mountains: false, kids: false },

  // Hygiëne
  { id: 'h1', name: 'Tandenborstel & tandpasta', category: 'Hygiëne', tripTypes: ['weekend', 'week', 'wandeltrip'], mountains: false, kids: false },
  { id: 'h2', name: 'Zeep / douche gel', category: 'Hygiëne', tripTypes: ['weekend', 'week', 'wandeltrip'], mountains: false, kids: false },
  { id: 'h3', name: 'Handdoeken (snel-droog)', category: 'Hygiëne', tripTypes: ['weekend', 'week', 'wandeltrip'], mountains: false, kids: false },
  { id: 'h4', name: 'Toiletpapier', category: 'Hygiëne', tripTypes: ['weekend', 'week', 'wandeldag', 'wandeltrip'], mountains: false, kids: false },
  { id: 'h5', name: 'Zonnebrandcrème', category: 'Hygiëne', tripTypes: ['weekend', 'week', 'wandeldag', 'wandeltrip'], mountains: false, kids: false },
  { id: 'h6', name: 'Insectenwerend middel', category: 'Hygiëne', tripTypes: ['weekend', 'week', 'wandeldag', 'wandeltrip'], mountains: false, kids: false },
  { id: 'h7', name: 'Nat doekjes', category: 'Hygiëne', tripTypes: ['weekend', 'week', 'wandeldag', 'wandeltrip'], mountains: false, kids: false },
  { id: 'h8', name: 'Luiers / zindelijkheidsspullen', category: 'Hygiëne', tripTypes: ['weekend', 'week', 'wandeldag', 'wandeltrip'], mountains: false, kids: true },
  { id: 'h9', name: 'Shampoo & conditioner', category: 'Hygiëne', tripTypes: ['weekend', 'week', 'wandeltrip'], mountains: false, kids: false },
  { id: 'h10', name: 'Deodorant', category: 'Hygiëne', tripTypes: ['weekend', 'week', 'wandeltrip'], mountains: false, kids: false },
  { id: 'h11', name: 'Scheerartikelen', category: 'Hygiëne', tripTypes: ['weekend', 'week', 'wandeltrip'], mountains: false, kids: false },

  // Kinderen
  { id: 'ki1', name: 'Kinderzonnebrandcrème (hoge factor)', category: 'Kinderen', tripTypes: ['weekend', 'week', 'wandeldag', 'wandeltrip'], mountains: false, kids: true },
  { id: 'ki2', name: 'Rugzak voor kinderen', category: 'Kinderen', tripTypes: ['weekend', 'week', 'wandeldag', 'wandeltrip'], mountains: false, kids: true },
  { id: 'ki3', name: 'Draagzak / kinderkraan', category: 'Kinderen', tripTypes: ['weekend', 'week', 'wandeldag', 'wandeltrip'], mountains: true, kids: true },
  { id: 'ki4', name: 'Speelgoed (klein & licht)', category: 'Kinderen', tripTypes: ['weekend', 'week', 'wandeltrip'], mountains: false, kids: true },
  { id: 'ki5', name: 'Geneesmiddelen kinderen (paracetamol etc.)', category: 'Kinderen', tripTypes: ['weekend', 'week', 'wandeldag', 'wandeltrip'], mountains: false, kids: true },
  { id: 'ki6', name: 'Verzorgingscrème / wondjes', category: 'Kinderen', tripTypes: ['weekend', 'week', 'wandeldag', 'wandeltrip'], mountains: false, kids: true },
  { id: 'ki7', name: 'Regen- en warmkleding kinderen', category: 'Kinderen', tripTypes: ['weekend', 'week', 'wandeldag', 'wandeltrip'], mountains: true, kids: true },
  { id: 'ki8', name: 'Boekjes / spelletjes voor avond', category: 'Kinderen', tripTypes: ['weekend', 'week', 'wandeltrip'], mountains: false, kids: true },

  // EHBO
  { id: 'e1', name: 'EHBO-kit', category: 'EHBO', tripTypes: ['weekend', 'week', 'wandeldag', 'wandeltrip'], mountains: false, kids: false },
  { id: 'e2', name: 'Pijnstillers', category: 'EHBO', tripTypes: ['weekend', 'week', 'wandeldag', 'wandeltrip'], mountains: false, kids: false },
  { id: 'e3', name: 'Pleister & verband', category: 'EHBO', tripTypes: ['weekend', 'week', 'wandeldag', 'wandeltrip'], mountains: false, kids: false },
  { id: 'e4', name: 'Teken-verwijderaar', category: 'EHBO', tripTypes: ['weekend', 'week', 'wandeldag', 'wandeltrip'], mountains: false, kids: false },
  { id: 'e5', name: 'Nooddeken (folie)', category: 'EHBO', tripTypes: ['weekend', 'week', 'wandeldag', 'wandeltrip'], mountains: true, kids: false },
  { id: 'e6', name: 'Antidiarreemiddel', category: 'EHBO', tripTypes: ['week', 'wandeltrip'], mountains: false, kids: false },

  // Navigatie
  { id: 'n1', name: 'Kaart van het gebied', category: 'Navigatie & Kaarten', tripTypes: ['weekend', 'week', 'wandeldag', 'wandeltrip'], mountains: false, kids: false },
  { id: 'n2', name: 'Kompas', category: 'Navigatie & Kaarten', tripTypes: ['weekend', 'week', 'wandeldag', 'wandeltrip'], mountains: true, kids: false },
  { id: 'n3', name: 'GPS / wandel-app (offline kaarten)', category: 'Navigatie & Kaarten', tripTypes: ['weekend', 'week', 'wandeldag', 'wandeltrip'], mountains: false, kids: false },
  { id: 'n4', name: 'Hoofdlamp + reservebatterijen', category: 'Navigatie & Kaarten', tripTypes: ['weekend', 'week', 'wandeltrip'], mountains: false, kids: false },

  // Gereedschap
  { id: 'g1', name: 'Zakmes / multitool', category: 'Gereedschap', tripTypes: ['weekend', 'week', 'wandeldag', 'wandeltrip'], mountains: false, kids: false },
  { id: 'g2', name: 'Touw / paracord', category: 'Gereedschap', tripTypes: ['weekend', 'week', 'wandeltrip'], mountains: false, kids: false },
  { id: 'g3', name: 'Haringen & hamer', category: 'Gereedschap', tripTypes: ['weekend', 'week'], mountains: false, kids: false },
  { id: 'g4', name: 'Duct tape', category: 'Gereedschap', tripTypes: ['weekend', 'week', 'wandeltrip'], mountains: false, kids: false },
  { id: 'g5', name: 'Powerbank', category: 'Gereedschap', tripTypes: ['weekend', 'week', 'wandeldag', 'wandeltrip'], mountains: false, kids: false },
  { id: 'g6', name: 'Klim-/wandelstokken', category: 'Gereedschap', tripTypes: ['weekend', 'week', 'wandeldag', 'wandeltrip'], mountains: true, kids: false },
  { id: 'g7', name: 'Pikhouweel / ijsbijl', category: 'Bergen', tripTypes: ['weekend', 'week', 'wandeltrip'], mountains: true, kids: false },
  { id: 'g8', name: 'Campingstoel', category: 'Gereedschap', tripTypes: ['weekend', 'week'], mountains: false, kids: false },
  { id: 'g9', name: 'Campingtafel', category: 'Gereedschap', tripTypes: ['weekend', 'week'], mountains: false, kids: false },
  { id: 'g10', name: 'Tentlamp / lantaarn', category: 'Gereedschap', tripTypes: ['weekend', 'week', 'wandeltrip'], mountains: false, kids: false },
  { id: 'g11', name: 'Verlengkabel / stekkerdoos', category: 'Gereedschap', tripTypes: ['weekend', 'week'], mountains: false, kids: false },

  // Overig
  { id: 'o1', name: 'Identiteitsbewijs / paspoort', category: 'Overig', tripTypes: ['week', 'wandeltrip'], mountains: false, kids: false },
  { id: 'o2', name: 'Verzekeringspas', category: 'Overig', tripTypes: ['week', 'wandeltrip'], mountains: false, kids: false },
  { id: 'o3', name: 'Geld / creditcard', category: 'Overig', tripTypes: ['weekend', 'week', 'wandeldag', 'wandeltrip'], mountains: false, kids: false },
  { id: 'o4', name: 'Telefoonoplader + adapter', category: 'Overig', tripTypes: ['weekend', 'week', 'wandeltrip'], mountains: false, kids: false },
  { id: 'o5', name: 'Campinggids / reserveringsbevestiging', category: 'Overig', tripTypes: ['weekend', 'week'], mountains: false, kids: false },

  // Berghut-specifiek
  { id: 'w1', name: 'Lakenzak', category: 'Slaap', tripTypes: ['wandeltrip'], mountains: false, kids: false },
  { id: 'w2', name: 'Berghutten reservering (bevestiging)', category: 'Overig', tripTypes: ['wandeltrip'], mountains: false, kids: false },
];

export const DEFAULT_TIPS: Tip[] = [
  {
    id: 't1',
    title: 'Paalsteek',
    category: 'Knopen',
    knotIcon: 'bowline-knot',
    content: 'De paalsteek maakt een vaste lus die niet strakker trekt onder belasting.\n\n1. Maak een kleine lus in het touw (heen gaan over het staande part)\n2. Steek het losse eind omhoog door de lus\n3. Ga achter het staande part langs\n4. Steek het losse eind terug door de lus naar beneden\n5. Trek stevig aan\n\nGebruik: tent vastzetten, reddingslijn, aan paal binden.',
    imageUrl: '/knots/paalsteek.webp',
  },
  {
    id: 't2',
    title: 'Schootsteek',
    category: 'Knopen',
    knotIcon: 'sheet-bend',
    content: 'Verbindt twee touwen van verschillende dikte.\n\n1. Maak een bocht in het dikste touw\n2. Steek het dunne touw door de bocht van onderaf\n3. Ga achter beide einden van de bocht langs\n4. Steek terug onder zichzelf door\n5. Trek stevig aan\n\nGebruik: twee touwen aan elkaar, tarp spannen.',
  },
  {
    id: 't3',
    title: 'Prusik',
    category: 'Knopen',
    knotIcon: 'prusik-knot',
    content: 'Glijdende klauwerknoop voor aan een touw.\n\n1. Neem een stuk dunner touw, maak er een lus van (vissersknoop)\n2. Wikkel de lus 3x om het staande touw\n3. Haal de lus door zichzelf\n4. Trek strak\n\nAangespannen: glijdt niet. Ontspannen: schuift langs het touw.\n\nGebruik: veiligheidsknoop bij klimmen, zelf-reddingsituaties.',
  },
  {
    id: 't9',
    title: 'Farrimond Friction Hitch',
    category: 'Knopen',
    knotIcon: 'farrimond-friction-hitch',
    content: 'Verstelbare frictie-knoop met snelle ontkoppeling. Top voor tarp- of waslijnen die je onder spanning wilt houden maar snel los wilt kunnen maken.\n\n1. Leid het werkende eind om een paal/boom\n2. Leg het werkende eind over het staande deel\n3. Maak een bocht (lus) en breng deze ónder het staande deel door\n4. Steek een tweede bocht (slipped) door deze eerste lus\n5. Trek aan het staande eind om vast te zetten\n6. Trekken aan het losse eind = direct los\n\nGebruik: tarp spannen, hangmat-lijnen, waslijn — overal waar je strak wilt en snel los wilt kunnen.',
  },
  {
    id: 't10',
    title: 'Mastworp (Clove Hitch)',
    category: 'Knopen',
    knotIcon: 'clove-hitch',
    content: 'Snel een touw aan een paal vastmaken.\n\n1. Wikkel het touw één keer om de paal\n2. Kruis er overheen en wikkel nog een keer\n3. Steek het einde onder de tweede wikkeling door\n4. Trek strak\n\nGebruik: tent-spanlijn aan paal, kano vastleggen, basis voor andere knopen.\n\nLet op: kan losschieten als de spanning eraf gaat — gebruik voor tijdelijke verbindingen.',
  },
  {
    id: 't4',
    title: 'Eten koken zonder stroom',
    category: 'Koken',
    content: 'Thermosgaar koken:\n1. Breng het water met bijv. pasta of rijst aan de kook\n2. Kook 2 minuten\n3. Stop de pan in een slaapzak of wikkel in een deken\n4. Laat 20-30 minuten staan\n5. Klaar! Bespaart veel gas.\n\nTip: werkt perfect op hoogte waar kookpunt lager ligt.',
  },
  {
    id: 't5',
    title: 'Hoogteproblemen voorkomen',
    category: 'Bergen',
    content: 'Boven 2500m:\n• Stijg niet meer dan 300-500m per dag in slaaphoogte\n• Drink veel water (3-4 liter per dag)\n• Eet koolhydraatrijk\n• Vermijd alcohol de eerste dagen\n• Bij hoofdpijn/misselijkheid: daal af en rust\n• Regel: "klimmen hoog, slapen laag"',
  },
  {
    id: 't7',
    title: 'Tarp spannen in regen',
    category: 'Knopen',
    content: 'Snel afdak met tarp:\n1. Zoek twee bomen op ~4m afstand\n2. Span een lijn tussen de bomen op ooghoogte\n3. Gooi de tarp over de lijn (asymmetrisch: meer aan één kant)\n4. Span de hoeken omlaag met haringen\n5. Trek de middenlijn strak\n\nTip: laat de voorkant hoger hangen dan de achterkant zodat regen wegglijdt.',
  },
  {
    id: 't8',
    title: 'Bliksemgevaar in de bergen',
    category: 'Bergen',
    content: '30-30 regel:\n• Als de tijd tussen bliksem en donder < 30 sec: zoek beschutting\n• Wacht 30 min na de laatste donderslag\n\nWat te doen:\n• Dalen of afdalen van open plekken\n• Niet onder de hoogste boom\n• Niet bij water blijven\n• Hurk neer op geïsoleerde ondergrond (rugzak)\n• Vermijd metalen voorwerpen',
  },
  {
    id: 't11',
    title: 'Tent verankeren bij sterke wind',
    category: 'Bergen',
    content: 'In de bergen kan de wind \'s nachts opsteken tot 60+ km/u. Voorkom dat je tent het begeeft:\n\n• Kies plek achter rotsblok of in een natuurlijke kom — niet op een bergrug\n• Oriënteer tent met smalle kant naar de wind\n• Gebruik alle stormlijnen, niet alleen de basis\n• Stenen op haringen leggen voor extra grip\n• Op rotsige bodem: V-vorm met zwaar gesteente of "deadman anchor" (zak met stenen ingegraven)\n• Spanlijnen onder 45° met de grond — sterker dan loodrecht\n\nTip: bij twijfel een nood-bivakplek lager zoeken in plaats van risico nemen.',
  },
  {
    id: 't12',
    title: 'Koken op hoogte',
    category: 'Bergen',
    content: 'Hoe hoger, hoe lager het kookpunt — op 3000m kookt water al bij ~90°C.\n\nGevolgen:\n• Pasta en rijst hebben 1.5-2x zoveel tijd nodig\n• Eieren worden niet hard\n• Brood rijst slechter\n\nTips:\n• Kies snelkokende ingrediënten (couscous, instant noedels, gevriesdroogd)\n• Pannendeksel altijd erop\n• Snijd groente in kleine stukjes\n• Reken extra gas (ca. +30% verbruik op 3000m)\n• Bij drinkwater zuiveren via koken: 3 minuten i.p.v. 1',
  },
  {
    id: 't13',
    title: 'Kleren in lagen (layering)',
    category: 'Bergen',
    content: 'In de bergen kan het temperatuurverschil 20°C per dag zijn. Drie lagen werken altijd:\n\n1. **Basislaag** (huid): merinowol of synthetisch — droogt snel, geen katoen\n2. **Isolatielaag**: fleece of donsjas — vasthouden warmte\n3. **Buitenlaag**: wind- en waterdicht (Gore-Tex of vergelijkbaar)\n\nRegel: liever koud bij vertrek dan zweten. Zweet onder een isolatielaag = onderkoeling als je stilstaat.\n\nExtra: muts (30% lichaamswarmte), handschoenen (extra paar reserve), warme sokken.',
  },
  {
    id: 't14',
    title: 'Kaart en kompas: peilen',
    category: 'Bergen',
    content: 'GPS kan uitvallen, batterij leeg, geen bereik. Basisvaardigheid:\n\n**Positie bepalen via triangulatie:**\n1. Identificeer 2-3 herkenbare punten in het landschap (top, kerk, kruis)\n2. Peil elk punt met kompas (richting in graden)\n3. Trek vanaf elk punt op de kaart een lijn in tegengestelde richting\n4. Waar de lijnen kruisen = jouw positie\n\n**Koers houden:**\n• Stel kompas in op gewenste koers\n• Loop richting een herkenningspunt op die koers\n• Als je dat bereikt, kies een nieuw punt verder weg\n• Houd zo een rechte lijn, ook in mist',
  },
  {
    id: 't15',
    title: 'Weersveranderingen lezen',
    category: 'Bergen',
    content: 'In de bergen kan het weer binnen 30 min compleet omslaan. Vroege signalen:\n\n• **Lensvormige wolken** boven toppen → sterke wind op komst\n• **Snelle drukval** (hoofdpijn, oren ploppen) → onweer dichtbij\n• **Stapelwolken die verticaal groeien** \'s ochtends → onweer in middag\n• **Wind draait plotseling** → frontale doorgang\n• **Plotselinge kou + windstilte** → onweer of front nadert\n\nVuistregel Alpen: vóór 14:00 op de top, vóór 16:00 weer in het dal. Onweer komt meestal \'s middags.',
  },
  {
    id: 't16',
    title: 'Veilig een bergrivier oversteken',
    category: 'Bergen',
    content: 'Bergrivieren stijgen \'s middags door smeltwater — \'s ochtends oversteken!\n\n**Bepalen of veilig:**\n• Niet dieper dan halverwege dij\n• Niet sneller dan stevige wandelpas (5 km/u)\n• Liever bredere, ondiepere plek dan smal en diep\n• Vermijd direct boven stroomversnelling\n\n**Techniek:**\n• Schoenen aanhouden! (anders verwondingen op stenen)\n• Heupgordel rugzak losmaken (kan eraf bij val)\n• Wandelstok stroomopwaarts als steunpunt\n• In groep: arm in arm, sterkste persoon stroomopwaarts\n• Diagonaal stroomafwaarts oversteken — niet recht tegen de stroom in',
  },
  {
    id: 't18',
    title: 'Noodkit: altijd meenemen',
    category: 'Bergen',
    content: 'Ongeacht de lengte van de tocht — altijd in je rugzak:\n\n• EHBO-kit (pleisters, zwachtels, pijnstillers, antibiotische zalf)\n• Thermische reddingsfolie (overlevingsdeken) — past in een vuist\n• Fluitje (3x blazen = noodsignaal)\n• Aansteker / lucifers in waterproof doosje\n• Zaklamp of hoofdlamp + reservebatterijen\n• Mes (multi-tool)\n• Extra eten (noodrantsoen: energierepen, noten)\n• Minstens 0.5L extra water\n• Powerbank voor telefoon\n• Notitie met naam, route en verwachte terugkomsttijd',
  },
  {
    id: 't19',
    title: 'SOS-signalen geven',
    category: 'Bergen',
    content: 'Als je hulp nodig hebt en geen telefoonbereik:\n\n**Universeel noodsignaal: 6x per minuut**\n• 6 fluitsignalen, 6 lichtflitsen of 6 roepen — dan 1 minuut pauze — herhaal\n• Reactie redder: 3x = bericht ontvangen\n\n**Zichtbare signalen:**\n• Reddingsfolie horizontaal uitleggen op open plek (zichtbaar vanuit helikopter)\n• Groot SOS in de sneeuw of met stenen (minstens 3m hoog)\n• Spiegelsignaal: zon reflecteren met telefoonscherm of glanzend oppervlak richting vliegtuig/helikopter\n\n**Via telefoon (ook zonder bereik):**\n• 112 werkt soms via elk beschikbaar netwerk\n• Zoek hoogste punt voor bereik\n• Sla exact GPS-coördinaat op (open kaart-app, bewaar locatie)',
  },
  {
    id: 't20',
    title: 'Sneeuwblindheid & UV op hoogte',
    category: 'Bergen',
    content: 'UV-straling neemt ~10% toe per 1000m hoogte. Op 3000m is de UV-intensiteit 30% hoger dan op zee.\n\n**Sneeuwblindheid (fotokeratitis):**\n• Ogen gaan pijn doen, tranen, gevoel van zand — pas uren later\n• Preventie: altijd zonnebril met 100% UV-bescherming (CAT 3 of 4 op gletsjers)\n• Zijwaartse bescherming nodig (gletsjer- of skibril)\n• Noodoplossing zonder bril: smalle spleet van karton/tape voor de ogen\n\n**Zonnebrand:**\n• Factor 50 op elke blootgestelde plek, ook lippen, oren, nek, onderkant neus\n• Elke 2 uur opnieuw smeren\n• Let op: bewolkt ≠ veilig — UV gaat door dunne wolken',
  },
  {
    id: 't17',
    title: 'Onderkoeling herkennen',
    category: 'Bergen',
    content: 'Onderkoeling sluipt erin. Letten op:\n\n**Mild (nog te helpen):**\n• Bibberen (oncontroleerbaar)\n• Onhandig, slordig spreken\n• Trage reacties\n\n**Ernstig (acute hulp nodig):**\n• Stopt met bibberen ondanks kou\n• Verwarring, irrationeel gedrag (mensen kleden zich soms uít)\n• Slaperigheid\n\n**Eerste hulp:**\n• Naar beschutte plek\n• Natte kleren uit, droge aan\n• In slaapzak met warm drinken (geen alcohol!)\n• Lichaam-aan-lichaam warmte als geen ander materiaal\n• NOOIT direct opwarmen (warme bad, kachel) — koud bloed naar hart = hartstilstand',
  },
];
